### ISSUE TITLE
Create Layer 1 UI

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/webdem.shamiit.org#1]
What to Do-

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/webdem.shamiit.org/assets/144815633/f0964de7-8d3c-4d08-9016-a7e520f66fdf)

Already Done-

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/webdem.shamiit.org/assets/144815633/3bfc4419-e8f2-4934-94a3-d36487396fa3)

What is Remaining-

Attached screenshot for reference-

![Image](https://github.com/shamiitltd/webdem.shamiit.org/assets/144815633/1efab77e-757f-4325-a448-b8a758d82ba0)

**Comment by helwadkarshramika3** [comment]
Attached Figma link below- 

https://www.figma.com/file/Lu9F4EmFCifGRpl04l9olX/UIUX-Team-For-Web-Dem?type=design&node-id=0%3A1&mode=design&t=fQgbFjq24nXWiFv6-1

**Comment by ShashikantPardhe2632** [comment]
Create Layer 1 UI Done!
