### ISSUE TITLE
Layer 1- Add Category UI

### ISSUE THREAD

**Issue by helwadkarshramika3** [shamiitltd/webdem.shamiit.org#2]
What to Do -

Attached screenshot for reference- 

![Image](https://github.com/shamiitltd/webdem.shamiit.org/assets/144815633/ad1eed52-71f5-4769-a0f9-0ad9dd21639f)

**Comment by helwadkarshramika3** [comment]
Attached Figma link below-

https://www.figma.com/file/Lu9F4EmFCifGRpl04l9olX/UIUX-Team-For-Web-Dem?type=design&node-id=0%3A1&mode=design&t=fQgbFjq24nXWiFv6-1 @sidharthchawla484

**Comment by pranavnavle** [comment]
Figma Updated

**Comment by ShashikantPardhe2632** [comment]
Layer 1- Add Category UI Done!
