### ISSUE TITLE
Layer 3 - Create table UI

### ISSUE THREAD

**Issue by pranavnavle** [shamiitltd/webdem.shamiit.org#26]
![Image](https://github.com/shamiitltd/webdem.shamiit.org/assets/124654793/6b1a34d7-f1ed-4b14-b69a-1f428e107553)

**Comment by ShashikantPardhe2632** [comment]
Layer3 UI Task Done!

**Comment by ShashikantPardhe2632** [comment]
Layer 3 - Create table UI Done!
